name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up -d --file docker-compose.yml --tag my-image-name:$(date +%s)
    - name: Entry in container
      run: docker compose exec app bash
    - name: Install Composer
      run: composer install
    - name: Generate Key
      run: php artisan key:generate
    - name: Import Migrations to database
      run: php artisan migrate
    - name: Populate database
      run: php artisan db:seed
